author: "Patrick Houtman - PH-F"
category: "http"
summary: "HTTP POST user's messages to target URL when user is offline for eJabberd 17.01"
home: "https://github.com/edwardchow33/mod_offline_http_post"
url: "https://github.com/edwardchow33/mod_offline_http_post"
